name: CI - Workflow

on: 
  push:
    branches: ['**']

  main-job:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046
        with:
          flutter-version: 3.29.3
          cache: true

      - name: ğŸŒ‹ Flutter pub get 
        run: flutter pub get

      - name: âœ¨ Flutter pub analyze
        run: flutter analyze

